### ISSUE TITLE
default transactionbuilder does not release inputs if transaction submit errors

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/rivine#587] opened 2019-09-13 07:36 UTC
Transactionbuilder locks the inputs it tries to use for the transaction. If the transaction submit fails, these inputs remain locked potentially causing all funds in the wallet to be locked until daemon restart.

**Comment by LeeSmet** [comment] 2019-09-23 07:56
Duplicate of #483

**Closed** 2019-10-02 14:36 UTC
Labels: state_inprogress, type_bug
